CREATE TYPE "account_type" AS ENUM ('human', 'robot', 'service');
--> statement-breakpoint
CREATE TYPE "permission_effect" AS ENUM ('allow', 'deny');
--> statement-breakpoint
CREATE TYPE "permission_scope" AS ENUM ('global', 'own', 'object');
--> statement-breakpoint
CREATE TYPE "problem_type" AS ENUM ('traditional', 'interactive', 'submit_answer');
--> statement-breakpoint
CREATE TYPE "problem_status" AS ENUM ('draft', 'pending_review', 'approved', 'rejected');
--> statement-breakpoint
CREATE TYPE "review_round_status" AS ENUM ('open', 'approved', 'rejected', 'withdrawn');
--> statement-breakpoint
CREATE TYPE "review_verdict" AS ENUM ('approve', 'request_changes', 'reject');
--> statement-breakpoint
CREATE TYPE "review_source" AS ENUM ('human', 'anklang', 'fermata', 'plugin');
--> statement-breakpoint
CREATE TYPE "review_item_visibility" AS ENUM ('author', 'reviewer', 'administrator');
--> statement-breakpoint
CREATE TYPE "plugin_state" AS ENUM ('enabled', 'disabled', 'unavailable');
--> statement-breakpoint
CREATE TYPE "file_purpose" AS ENUM ('problem', 'import_input', 'export_output', 'temporary');
--> statement-breakpoint
CREATE TYPE "problem_file_category" AS ENUM (
  'statement_image',
  'public_attachment',
  'internal_attachment',
  'testdata',
  'checker',
  'interactor',
  'answer_checker',
  'standard_solution'
);
--> statement-breakpoint
CREATE TYPE "contest_state" AS ENUM ('draft', 'locked', 'archived');
--> statement-breakpoint
CREATE TYPE "contest_member_role" AS ENUM ('participant', 'manager');
--> statement-breakpoint
CREATE TYPE "task_state" AS ENUM ('queued', 'running', 'succeeded', 'failed', 'cancelled');
--> statement-breakpoint
CREATE TYPE "audit_result" AS ENUM ('success', 'denied', 'failure');
--> statement-breakpoint

CREATE TABLE "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "users_id_seq" START WITH 1) PRIMARY KEY,
  "nickname" varchar(120) NOT NULL,
  "account_type" "account_type" NOT NULL DEFAULT 'human',
  "password_hash" text,
  "auth_revision" integer NOT NULL DEFAULT 1,
  "password_changed_at" timestamptz,
  "disabled_at" timestamptz,
  "disabled_reason" varchar(500),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "users_nonnegative_id_ck" CHECK ("id" >= 0),
  CONSTRAINT "users_auth_revision_ck" CHECK ("auth_revision" > 0),
  CONSTRAINT "users_root_is_human_ck" CHECK ("id" <> 0 OR "account_type" = 'human')
);
--> statement-breakpoint
CREATE INDEX "users_account_type_idx" ON "users" ("account_type");
--> statement-breakpoint
CREATE INDEX "users_active_idx" ON "users" ("disabled_at");
--> statement-breakpoint

CREATE TABLE "user_emails" (
  "id" uuid PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "address" varchar(320) NOT NULL,
  "normalized_address" varchar(320) NOT NULL,
  "is_primary" boolean NOT NULL DEFAULT false,
  "verified_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "user_emails_normalized_ck"
    CHECK ("normalized_address" = lower(btrim("normalized_address"))),
  CONSTRAINT "user_emails_not_blank_ck" CHECK (length(btrim("address")) > 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "user_emails_normalized_uq" ON "user_emails" ("normalized_address");
--> statement-breakpoint
CREATE UNIQUE INDEX "user_emails_one_primary_uq"
  ON "user_emails" ("user_id") WHERE "is_primary" = true;
--> statement-breakpoint
CREATE INDEX "user_emails_user_idx" ON "user_emails" ("user_id");
--> statement-breakpoint

CREATE TABLE "external_identities" (
  "id" uuid PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "provider" varchar(80) NOT NULL,
  "subject" varchar(255) NOT NULL,
  "profile" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "last_authenticated_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "external_identities_provider_ck" CHECK (length(btrim("provider")) > 0),
  CONSTRAINT "external_identities_subject_ck" CHECK (length(btrim("subject")) > 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "external_identities_provider_subject_uq"
  ON "external_identities" ("provider", "subject");
--> statement-breakpoint
CREATE INDEX "external_identities_user_idx" ON "external_identities" ("user_id");
--> statement-breakpoint

CREATE TABLE "user_identifiers" (
  "id" uuid PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "kind" varchar(80) NOT NULL,
  "value" varchar(255) NOT NULL,
  "source" varchar(120) NOT NULL,
  "valid_from" timestamptz,
  "valid_until" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "user_identifiers_valid_range_ck"
    CHECK ("valid_until" IS NULL OR "valid_from" IS NULL OR "valid_until" > "valid_from")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "user_identifiers_source_value_uq"
  ON "user_identifiers" ("kind", "source", "value");
--> statement-breakpoint
CREATE INDEX "user_identifiers_user_idx" ON "user_identifiers" ("user_id");
--> statement-breakpoint
CREATE INDEX "user_identifiers_lookup_idx" ON "user_identifiers" ("kind", "value");
--> statement-breakpoint

CREATE TABLE "permission_definitions" (
  "name" varchar(160) PRIMARY KEY,
  "display_name" varchar(120) NOT NULL,
  "description" text NOT NULL,
  "source" varchar(160) NOT NULL DEFAULT 'core',
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "permission_definitions_name_ck"
    CHECK ("name" ~ '^[a-z0-9]+([._-][a-z0-9]+)*$')
);
--> statement-breakpoint
CREATE INDEX "permission_definitions_source_idx" ON "permission_definitions" ("source");
--> statement-breakpoint

CREATE TABLE "roles" (
  "id" uuid PRIMARY KEY,
  "key" varchar(80) NOT NULL,
  "display_name" varchar(120) NOT NULL,
  "description" text NOT NULL,
  "is_built_in" boolean NOT NULL DEFAULT false,
  "created_by_user_id" bigint REFERENCES "users" ("id") ON DELETE SET NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "roles_key_ck" CHECK ("key" ~ '^[a-z0-9]+([_-][a-z0-9]+)*$')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "roles_key_uq" ON "roles" ("key");
--> statement-breakpoint

CREATE TABLE "role_memberships" (
  "id" uuid PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "role_id" uuid NOT NULL REFERENCES "roles" ("id") ON DELETE CASCADE,
  "granted_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "reason" varchar(500) NOT NULL,
  "expires_at" timestamptz,
  "revoked_at" timestamptz,
  "revoked_by_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "role_memberships_revoke_ck" CHECK (
    ("revoked_at" IS NULL AND "revoked_by_user_id" IS NULL)
    OR ("revoked_at" IS NOT NULL AND "revoked_by_user_id" IS NOT NULL)
  ),
  CONSTRAINT "role_memberships_expiry_ck"
    CHECK ("expires_at" IS NULL OR "expires_at" > "created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "role_memberships_active_uq"
  ON "role_memberships" ("user_id", "role_id") WHERE "revoked_at" IS NULL;
--> statement-breakpoint
CREATE INDEX "role_memberships_role_idx" ON "role_memberships" ("role_id");
--> statement-breakpoint

CREATE TABLE "permission_grants" (
  "id" uuid PRIMARY KEY,
  "subject_user_id" bigint REFERENCES "users" ("id") ON DELETE CASCADE,
  "subject_role_id" uuid REFERENCES "roles" ("id") ON DELETE CASCADE,
  "permission_name" varchar(160) NOT NULL
    REFERENCES "permission_definitions" ("name") ON DELETE RESTRICT,
  "effect" "permission_effect" NOT NULL,
  "scope" "permission_scope" NOT NULL,
  "object_type" varchar(80),
  "object_id" varchar(160),
  "expires_at" timestamptz,
  "granted_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "reason" varchar(500) NOT NULL,
  "revoked_at" timestamptz,
  "revoked_by_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "permission_grants_one_subject_ck"
    CHECK (num_nonnulls("subject_user_id", "subject_role_id") = 1),
  CONSTRAINT "permission_grants_scope_ck" CHECK (
    ("scope" = 'object' AND "object_type" IS NOT NULL AND "object_id" IS NOT NULL)
    OR ("scope" <> 'object' AND "object_type" IS NULL AND "object_id" IS NULL)
  ),
  CONSTRAINT "permission_grants_revoke_ck" CHECK (
    ("revoked_at" IS NULL AND "revoked_by_user_id" IS NULL)
    OR ("revoked_at" IS NOT NULL AND "revoked_by_user_id" IS NOT NULL)
  )
);
--> statement-breakpoint
CREATE INDEX "permission_grants_user_lookup_idx"
  ON "permission_grants" ("subject_user_id", "permission_name", "effect", "scope");
--> statement-breakpoint
CREATE INDEX "permission_grants_role_lookup_idx"
  ON "permission_grants" ("subject_role_id", "permission_name", "effect", "scope");
--> statement-breakpoint
CREATE INDEX "permission_grants_object_lookup_idx"
  ON "permission_grants" ("object_type", "object_id");
--> statement-breakpoint

CREATE TABLE "sessions" (
  "id" uuid PRIMARY KEY,
  "token_digest" char(64) NOT NULL,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "impersonator_user_id" bigint REFERENCES "users" ("id") ON DELETE CASCADE,
  "auth_revision" integer NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "last_used_at" timestamptz,
  "revoked_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "sessions_digest_ck" CHECK ("token_digest" ~ '^[0-9a-f]{64}$'),
  CONSTRAINT "sessions_auth_revision_ck" CHECK ("auth_revision" > 0),
  CONSTRAINT "sessions_expiry_ck" CHECK ("expires_at" > "created_at"),
  CONSTRAINT "sessions_impersonator_ck"
    CHECK ("impersonator_user_id" IS NULL OR "impersonator_user_id" <> "user_id")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "sessions_token_digest_uq" ON "sessions" ("token_digest");
--> statement-breakpoint
CREATE INDEX "sessions_user_active_idx" ON "sessions" ("user_id", "expires_at");
--> statement-breakpoint
CREATE INDEX "sessions_expiry_idx" ON "sessions" ("expires_at");
--> statement-breakpoint

CREATE TABLE "api_tokens" (
  "id" uuid PRIMARY KEY,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "name" varchar(120) NOT NULL,
  "token_prefix" varchar(24) NOT NULL,
  "token_digest" char(64) NOT NULL,
  "source_cidrs" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "expires_at" timestamptz,
  "last_used_at" timestamptz,
  "revoked_at" timestamptz,
  "created_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "api_tokens_digest_ck" CHECK ("token_digest" ~ '^[0-9a-f]{64}$'),
  CONSTRAINT "api_tokens_expiry_ck"
    CHECK ("expires_at" IS NULL OR "expires_at" > "created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "api_tokens_digest_uq" ON "api_tokens" ("token_digest");
--> statement-breakpoint
CREATE INDEX "api_tokens_user_active_idx" ON "api_tokens" ("user_id", "expires_at");
--> statement-breakpoint

CREATE TABLE "api_token_permissions" (
  "id" uuid PRIMARY KEY,
  "token_id" uuid NOT NULL REFERENCES "api_tokens" ("id") ON DELETE CASCADE,
  "permission_name" varchar(160) NOT NULL
    REFERENCES "permission_definitions" ("name") ON DELETE RESTRICT,
  "effect" "permission_effect" NOT NULL DEFAULT 'allow',
  "scope" "permission_scope" NOT NULL,
  "object_type" varchar(80),
  "object_id" varchar(160),
  CONSTRAINT "api_token_permissions_scope_ck" CHECK (
    ("scope" = 'object' AND "object_type" IS NOT NULL AND "object_id" IS NOT NULL)
    OR ("scope" <> 'object' AND "object_type" IS NULL AND "object_id" IS NULL)
  )
);
--> statement-breakpoint
CREATE INDEX "api_token_permissions_lookup_idx"
  ON "api_token_permissions" ("token_id", "permission_name", "effect");
--> statement-breakpoint

CREATE TABLE "installed_plugins" (
  "id" varchar(160) PRIMARY KEY,
  "display_name" varchar(120) NOT NULL,
  "version" varchar(80) NOT NULL,
  "api_version" varchar(40) NOT NULL,
  "source" varchar(500) NOT NULL,
  "manifest_digest" char(64) NOT NULL,
  "state" "plugin_state" NOT NULL DEFAULT 'disabled',
  "failure_code" varchar(120),
  "installed_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "installed_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "installed_plugins_id_ck" CHECK ("id" ~ '^[a-z0-9]+([._-][a-z0-9]+)*$'),
  CONSTRAINT "installed_plugins_digest_ck"
    CHECK ("manifest_digest" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE INDEX "installed_plugins_state_idx" ON "installed_plugins" ("state");
--> statement-breakpoint

CREATE TABLE "plugin_settings" (
  "plugin_id" varchar(160) PRIMARY KEY
    REFERENCES "installed_plugins" ("id") ON DELETE CASCADE,
  "settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "revision" integer NOT NULL DEFAULT 1,
  "updated_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "plugin_settings_revision_ck" CHECK ("revision" > 0)
);
--> statement-breakpoint

CREATE TABLE "plugin_secrets" (
  "plugin_id" varchar(160) NOT NULL REFERENCES "installed_plugins" ("id") ON DELETE CASCADE,
  "name" varchar(120) NOT NULL,
  "encrypted_value" text NOT NULL,
  "key_version" integer NOT NULL,
  "masked_suffix" varchar(16) NOT NULL DEFAULT '',
  "updated_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "plugin_secrets_pk" PRIMARY KEY ("plugin_id", "name"),
  CONSTRAINT "plugin_secrets_key_version_ck" CHECK ("key_version" > 0)
);
--> statement-breakpoint

CREATE TABLE "problems" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "problems_id_seq" START WITH 1) PRIMARY KEY,
  "owner_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "status" "problem_status" NOT NULL DEFAULT 'draft',
  "current_revision" integer NOT NULL DEFAULT 1,
  "current_review_round" integer NOT NULL DEFAULT 0,
  "status_changed_by_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "status_reason" varchar(500),
  "deleted_at" timestamptz,
  "deleted_by_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "problems_positive_revision_ck" CHECK ("current_revision" > 0),
  CONSTRAINT "problems_review_round_ck" CHECK ("current_review_round" >= 0),
  CONSTRAINT "problems_delete_ck" CHECK (
    ("deleted_at" IS NULL AND "deleted_by_user_id" IS NULL)
    OR ("deleted_at" IS NOT NULL AND "deleted_by_user_id" IS NOT NULL)
  )
);
--> statement-breakpoint
CREATE INDEX "problems_owner_status_idx" ON "problems" ("owner_id", "status");
--> statement-breakpoint
CREATE INDEX "problems_status_updated_idx" ON "problems" ("status", "updated_at");
--> statement-breakpoint
CREATE INDEX "problems_not_deleted_idx" ON "problems" ("id") WHERE "deleted_at" IS NULL;
--> statement-breakpoint

CREATE TABLE "problem_revisions" (
  "id" uuid PRIMARY KEY,
  "problem_id" bigint NOT NULL REFERENCES "problems" ("id") ON DELETE CASCADE,
  "revision" integer NOT NULL,
  "status" "problem_status" NOT NULL,
  "title" varchar(200) NOT NULL,
  "type" "problem_type" NOT NULL,
  "codeforces_difficulty" smallint,
  "thinking_level" smallint,
  "coding_level" smallint,
  "basic_statement" text NOT NULL,
  "basic_solution" text NOT NULL,
  "background" text NOT NULL DEFAULT '',
  "statement" text NOT NULL DEFAULT '',
  "input_format" text NOT NULL DEFAULT '',
  "output_format" text NOT NULL DEFAULT '',
  "constraints" text NOT NULL DEFAULT '',
  "solution" text NOT NULL DEFAULT '',
  "hints" text NOT NULL DEFAULT '',
  "judge_config" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "format_extensions" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "changed_fields" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "content_hash" char(64) NOT NULL,
  "change_reason" varchar(500) NOT NULL,
  "created_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "problem_revisions_revision_ck" CHECK ("revision" > 0),
  CONSTRAINT "problem_revisions_title_ck" CHECK (length(btrim("title")) > 0),
  CONSTRAINT "problem_revisions_cf_difficulty_ck" CHECK (
    "codeforces_difficulty" IS NULL
    OR ("codeforces_difficulty" BETWEEN 800 AND 3500 AND "codeforces_difficulty" % 100 = 0)
  ),
  CONSTRAINT "problem_revisions_thinking_level_ck"
    CHECK ("thinking_level" IS NULL OR "thinking_level" BETWEEN 1 AND 5),
  CONSTRAINT "problem_revisions_coding_level_ck"
    CHECK ("coding_level" IS NULL OR "coding_level" BETWEEN 1 AND 5),
  CONSTRAINT "problem_revisions_content_hash_ck"
    CHECK ("content_hash" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "problem_revisions_problem_revision_uq"
  ON "problem_revisions" ("problem_id", "revision");
--> statement-breakpoint
CREATE UNIQUE INDEX "problem_revisions_problem_id_id_uq"
  ON "problem_revisions" ("problem_id", "id");
--> statement-breakpoint
CREATE INDEX "problem_revisions_problem_created_idx"
  ON "problem_revisions" ("problem_id", "created_at");
--> statement-breakpoint
CREATE INDEX "problem_revisions_content_hash_idx" ON "problem_revisions" ("content_hash");
--> statement-breakpoint
CREATE INDEX "problem_revisions_title_lower_idx" ON "problem_revisions" (lower("title"));
--> statement-breakpoint
ALTER TABLE "problems"
  ADD CONSTRAINT "problems_current_revision_fk"
  FOREIGN KEY ("id", "current_revision")
  REFERENCES "problem_revisions" ("problem_id", "revision")
  DEFERRABLE INITIALLY DEFERRED;
--> statement-breakpoint

CREATE TABLE "tags" (
  "id" varchar(120) PRIMARY KEY,
  "parent_id" varchar(120) REFERENCES "tags" ("id") ON DELETE RESTRICT,
  "name" varchar(80) NOT NULL,
  "group_name" varchar(80) NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_by_user_id" bigint REFERENCES "users" ("id") ON DELETE SET NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "tags_not_self_parent_ck" CHECK ("parent_id" IS NULL OR "parent_id" <> "id")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "tags_parent_name_uq" ON "tags" ("parent_id", "name");
--> statement-breakpoint
CREATE INDEX "tags_group_sort_idx" ON "tags" ("group_name", "sort_order");
--> statement-breakpoint

CREATE TABLE "problem_revision_tags" (
  "revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE CASCADE,
  "tag_id" varchar(120) NOT NULL REFERENCES "tags" ("id") ON DELETE RESTRICT,
  CONSTRAINT "problem_revision_tags_pk" PRIMARY KEY ("revision_id", "tag_id")
);
--> statement-breakpoint
CREATE INDEX "problem_revision_tags_tag_idx"
  ON "problem_revision_tags" ("tag_id", "revision_id");
--> statement-breakpoint

CREATE TABLE "problem_samples" (
  "id" uuid NOT NULL,
  "revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE CASCADE,
  "position" smallint NOT NULL,
  "input" text NOT NULL,
  "output" text NOT NULL,
  "explanation" text NOT NULL DEFAULT '',
  CONSTRAINT "problem_samples_pk" PRIMARY KEY ("revision_id", "id"),
  CONSTRAINT "problem_samples_position_ck" CHECK ("position" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "problem_samples_revision_position_uq"
  ON "problem_samples" ("revision_id", "position");
--> statement-breakpoint

CREATE TABLE "stored_files" (
  "id" uuid PRIMARY KEY,
  "purpose" "file_purpose" NOT NULL,
  "storage_key" varchar(1024) NOT NULL,
  "original_name" varchar(500) NOT NULL,
  "media_type" varchar(255) NOT NULL,
  "byte_size" bigint NOT NULL,
  "sha256" char(64) NOT NULL,
  "created_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "expires_at" timestamptz,
  "deleted_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "stored_files_size_ck" CHECK ("byte_size" >= 0),
  CONSTRAINT "stored_files_sha256_ck" CHECK ("sha256" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "stored_files_storage_key_uq" ON "stored_files" ("storage_key");
--> statement-breakpoint
CREATE INDEX "stored_files_expiry_idx" ON "stored_files" ("expires_at");
--> statement-breakpoint
CREATE INDEX "stored_files_digest_idx" ON "stored_files" ("sha256", "byte_size");
--> statement-breakpoint

CREATE TABLE "problem_revision_files" (
  "revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE CASCADE,
  "file_id" uuid NOT NULL REFERENCES "stored_files" ("id") ON DELETE RESTRICT,
  "category" "problem_file_category" NOT NULL,
  "logical_path" varchar(1024) NOT NULL,
  "position" integer NOT NULL DEFAULT 0,
  CONSTRAINT "problem_revision_files_pk" PRIMARY KEY ("revision_id", "file_id"),
  CONSTRAINT "problem_revision_files_position_ck" CHECK ("position" >= 0),
  CONSTRAINT "problem_revision_files_path_ck"
    CHECK ("logical_path" !~ '(^/|\\|(^|/)\.\.(/|$))')
);
--> statement-breakpoint
CREATE UNIQUE INDEX "problem_revision_files_path_uq"
  ON "problem_revision_files" ("revision_id", "logical_path");
--> statement-breakpoint
CREATE INDEX "problem_revision_files_file_idx" ON "problem_revision_files" ("file_id");
--> statement-breakpoint

CREATE TABLE "review_rounds" (
  "id" uuid PRIMARY KEY,
  "problem_id" bigint NOT NULL REFERENCES "problems" ("id") ON DELETE CASCADE,
  "round" integer NOT NULL,
  "submitted_revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE RESTRICT,
  "status" "review_round_status" NOT NULL DEFAULT 'open',
  "rule_id" varchar(160) NOT NULL,
  "rule_settings" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "submitted_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "decided_by_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "decision_reason" varchar(1000),
  "decided_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "review_rounds_problem_revision_fk"
    FOREIGN KEY ("problem_id", "submitted_revision_id")
    REFERENCES "problem_revisions" ("problem_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "review_rounds_round_ck" CHECK ("round" > 0),
  CONSTRAINT "review_rounds_decision_ck" CHECK (
    ("status" = 'open' AND "decided_at" IS NULL AND "decided_by_user_id" IS NULL)
    OR ("status" <> 'open' AND "decided_at" IS NOT NULL)
  )
);
--> statement-breakpoint
CREATE UNIQUE INDEX "review_rounds_problem_round_uq"
  ON "review_rounds" ("problem_id", "round");
--> statement-breakpoint
CREATE UNIQUE INDEX "review_rounds_one_open_uq"
  ON "review_rounds" ("problem_id") WHERE "status" = 'open';
--> statement-breakpoint
CREATE INDEX "review_rounds_status_created_idx" ON "review_rounds" ("status", "created_at");
--> statement-breakpoint

CREATE TABLE "review_opinions" (
  "id" uuid PRIMARY KEY,
  "round_id" uuid NOT NULL REFERENCES "review_rounds" ("id") ON DELETE CASCADE,
  "reviewer_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "source" "review_source" NOT NULL,
  "verdict" "review_verdict" NOT NULL,
  "codeforces_difficulty" smallint NOT NULL,
  "quality_level" smallint NOT NULL,
  "thinking_level" smallint NOT NULL,
  "coding_level" smallint NOT NULL,
  "improvements" text NOT NULL,
  "public_comment" text NOT NULL DEFAULT '',
  "private_note" text NOT NULL DEFAULT '',
  "is_active" boolean NOT NULL DEFAULT true,
  "invalidated_at" timestamptz,
  "invalidation_reason" varchar(500),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "review_opinions_cf_difficulty_ck" CHECK (
    "codeforces_difficulty" BETWEEN 800 AND 3500
    AND "codeforces_difficulty" % 100 = 0
  ),
  CONSTRAINT "review_opinions_quality_level_ck" CHECK ("quality_level" BETWEEN 1 AND 5),
  CONSTRAINT "review_opinions_thinking_level_ck" CHECK ("thinking_level" BETWEEN 1 AND 5),
  CONSTRAINT "review_opinions_coding_level_ck" CHECK ("coding_level" BETWEEN 1 AND 5),
  CONSTRAINT "review_opinions_improvements_ck" CHECK (length(btrim("improvements")) > 0),
  CONSTRAINT "review_opinions_invalidation_ck" CHECK (
    (
      "is_active" = true
      AND "invalidated_at" IS NULL
      AND "invalidation_reason" IS NULL
    )
    OR (
      "is_active" = false
      AND "invalidated_at" IS NOT NULL
      AND "invalidation_reason" IS NOT NULL
    )
  )
);
--> statement-breakpoint
CREATE UNIQUE INDEX "review_opinions_active_reviewer_uq"
  ON "review_opinions" ("round_id", "reviewer_user_id") WHERE "is_active" = true;
--> statement-breakpoint
CREATE INDEX "review_opinions_round_verdict_idx"
  ON "review_opinions" ("round_id", "verdict");
--> statement-breakpoint

CREATE TABLE "review_assignments" (
  "id" uuid PRIMARY KEY,
  "round_id" uuid NOT NULL REFERENCES "review_rounds" ("id") ON DELETE CASCADE,
  "reviewer_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "assigned_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "reason" varchar(500) NOT NULL DEFAULT '',
  "expires_at" timestamptz,
  "revoked_at" timestamptz,
  "revoked_by_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "review_assignments_revoke_ck" CHECK (
    ("revoked_at" IS NULL AND "revoked_by_user_id" IS NULL)
    OR ("revoked_at" IS NOT NULL AND "revoked_by_user_id" IS NOT NULL)
  ),
  CONSTRAINT "review_assignments_expiry_ck"
    CHECK ("expires_at" IS NULL OR "expires_at" > "created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX "review_assignments_active_reviewer_uq"
  ON "review_assignments" ("round_id", "reviewer_user_id") WHERE "revoked_at" IS NULL;
--> statement-breakpoint
CREATE INDEX "review_assignments_reviewer_idx"
  ON "review_assignments" ("reviewer_user_id", "expires_at");
--> statement-breakpoint

CREATE TABLE "review_opinion_tags" (
  "opinion_id" uuid NOT NULL REFERENCES "review_opinions" ("id") ON DELETE CASCADE,
  "tag_id" varchar(120) NOT NULL REFERENCES "tags" ("id") ON DELETE RESTRICT,
  CONSTRAINT "review_opinion_tags_pk" PRIMARY KEY ("opinion_id", "tag_id")
);
--> statement-breakpoint
CREATE INDEX "review_opinion_tags_tag_idx" ON "review_opinion_tags" ("tag_id");
--> statement-breakpoint

CREATE TABLE "review_items" (
  "id" uuid PRIMARY KEY,
  "round_id" uuid NOT NULL REFERENCES "review_rounds" ("id") ON DELETE CASCADE,
  "type" varchar(160) NOT NULL,
  "source" "review_source" NOT NULL,
  "source_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "source_plugin_id" varchar(160) REFERENCES "installed_plugins" ("id") ON DELETE SET NULL,
  "visibility" "review_item_visibility" NOT NULL,
  "summary" varchar(500) NOT NULL,
  "data" jsonb NOT NULL,
  "content_hash" char(64) NOT NULL,
  "expires_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "review_items_summary_ck" CHECK (length(btrim("summary")) > 0),
  CONSTRAINT "review_items_content_hash_ck" CHECK ("content_hash" ~ '^[0-9a-f]{64}$'),
  CONSTRAINT "review_items_source_ck"
    CHECK (num_nonnulls("source_user_id", "source_plugin_id") >= 1)
);
--> statement-breakpoint
CREATE INDEX "review_items_round_type_idx" ON "review_items" ("round_id", "type");
--> statement-breakpoint
CREATE INDEX "review_items_content_hash_idx" ON "review_items" ("content_hash");
--> statement-breakpoint

CREATE TABLE "problem_access_aggregates" (
  "problem_id" bigint NOT NULL REFERENCES "problems" ("id") ON DELETE CASCADE,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "first_accessed_at" timestamptz NOT NULL,
  "last_accessed_at" timestamptz NOT NULL,
  "total_active_seconds" bigint NOT NULL DEFAULT 0,
  "last_revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE RESTRICT,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "problem_access_aggregates_pk" PRIMARY KEY ("problem_id", "user_id"),
  CONSTRAINT "problem_access_aggregates_problem_revision_fk"
    FOREIGN KEY ("problem_id", "last_revision_id")
    REFERENCES "problem_revisions" ("problem_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "problem_access_aggregates_time_ck"
    CHECK ("last_accessed_at" >= "first_accessed_at"),
  CONSTRAINT "problem_access_aggregates_duration_ck" CHECK ("total_active_seconds" >= 0)
);
--> statement-breakpoint
CREATE INDEX "problem_access_aggregates_user_idx"
  ON "problem_access_aggregates" ("user_id", "last_accessed_at");
--> statement-breakpoint

CREATE TABLE "contests" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "contests_id_seq" START WITH 1) PRIMARY KEY,
  "title" varchar(200) NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "state" "contest_state" NOT NULL DEFAULT 'draft',
  "starts_at" timestamptz,
  "ends_at" timestamptz,
  "created_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "deleted_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "contests_title_ck" CHECK (length(btrim("title")) > 0),
  CONSTRAINT "contests_time_range_ck"
    CHECK ("ends_at" IS NULL OR "starts_at" IS NULL OR "ends_at" > "starts_at")
);
--> statement-breakpoint
CREATE INDEX "contests_creator_state_idx" ON "contests" ("created_by_user_id", "state");
--> statement-breakpoint

CREATE TABLE "contest_members" (
  "contest_id" bigint NOT NULL REFERENCES "contests" ("id") ON DELETE CASCADE,
  "user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE CASCADE,
  "role" "contest_member_role" NOT NULL DEFAULT 'participant',
  "added_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "contest_members_pk" PRIMARY KEY ("contest_id", "user_id")
);
--> statement-breakpoint
CREATE INDEX "contest_members_user_idx" ON "contest_members" ("user_id", "contest_id");
--> statement-breakpoint

CREATE TABLE "contest_problems" (
  "contest_id" bigint NOT NULL REFERENCES "contests" ("id") ON DELETE CASCADE,
  "position" smallint NOT NULL,
  "problem_id" bigint NOT NULL REFERENCES "problems" ("id") ON DELETE RESTRICT,
  "revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE RESTRICT,
  "score" integer NOT NULL,
  "estimated_difficulty" smallint,
  "leak_risk" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "added_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "contest_problems_pk" PRIMARY KEY ("contest_id", "position"),
  CONSTRAINT "contest_problems_problem_revision_fk"
    FOREIGN KEY ("problem_id", "revision_id")
    REFERENCES "problem_revisions" ("problem_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "contest_problems_position_ck" CHECK ("position" >= 0),
  CONSTRAINT "contest_problems_score_ck" CHECK ("score" > 0),
  CONSTRAINT "contest_problems_difficulty_ck"
    CHECK ("estimated_difficulty" IS NULL OR "estimated_difficulty" BETWEEN 1 AND 5)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "contest_problems_problem_uq"
  ON "contest_problems" ("contest_id", "problem_id");
--> statement-breakpoint
CREATE INDEX "contest_problems_revision_idx" ON "contest_problems" ("revision_id");
--> statement-breakpoint

CREATE TABLE "import_jobs" (
  "id" uuid PRIMARY KEY,
  "requested_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "source_file_id" uuid NOT NULL REFERENCES "stored_files" ("id") ON DELETE RESTRICT,
  "detected_format" varchar(160),
  "selected_format" varchar(160) NOT NULL,
  "input_digest" char(64) NOT NULL,
  "choices" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "state" "task_state" NOT NULL DEFAULT 'queued',
  "progress_percent" smallint NOT NULL DEFAULT 0,
  "report" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "failure_code" varchar(120),
  "failure_message" varchar(1000),
  "idempotency_key" varchar(160) NOT NULL,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "import_jobs_digest_ck" CHECK ("input_digest" ~ '^[0-9a-f]{64}$'),
  CONSTRAINT "import_jobs_progress_ck" CHECK ("progress_percent" BETWEEN 0 AND 100)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "import_jobs_request_idempotency_uq"
  ON "import_jobs" ("requested_by_user_id", "idempotency_key");
--> statement-breakpoint
CREATE INDEX "import_jobs_state_created_idx" ON "import_jobs" ("state", "created_at");
--> statement-breakpoint

CREATE TABLE "import_job_items" (
  "job_id" uuid NOT NULL REFERENCES "import_jobs" ("id") ON DELETE CASCADE,
  "position" integer NOT NULL,
  "source_label" varchar(200) NOT NULL,
  "state" "task_state" NOT NULL DEFAULT 'queued',
  "imported_problem_id" bigint REFERENCES "problems" ("id") ON DELETE SET NULL,
  "report" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "failure_code" varchar(120),
  "failure_message" varchar(1000),
  "finished_at" timestamptz,
  CONSTRAINT "import_job_items_pk" PRIMARY KEY ("job_id", "position"),
  CONSTRAINT "import_job_items_position_ck" CHECK ("position" >= 0)
);
--> statement-breakpoint

CREATE TABLE "export_jobs" (
  "id" uuid PRIMARY KEY,
  "requested_by_user_id" bigint NOT NULL REFERENCES "users" ("id") ON DELETE RESTRICT,
  "target_format" varchar(160) NOT NULL,
  "options" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "loss_report" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "state" "task_state" NOT NULL DEFAULT 'queued',
  "progress_percent" smallint NOT NULL DEFAULT 0,
  "result_file_id" uuid REFERENCES "stored_files" ("id") ON DELETE SET NULL,
  "failure_code" varchar(120),
  "failure_message" varchar(1000),
  "idempotency_key" varchar(160) NOT NULL,
  "result_expires_at" timestamptz,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "export_jobs_progress_ck" CHECK ("progress_percent" BETWEEN 0 AND 100),
  CONSTRAINT "export_jobs_result_ck" CHECK (
    "state" <> 'succeeded'
    OR ("result_file_id" IS NOT NULL AND "result_expires_at" IS NOT NULL)
  )
);
--> statement-breakpoint
CREATE UNIQUE INDEX "export_jobs_request_idempotency_uq"
  ON "export_jobs" ("requested_by_user_id", "idempotency_key");
--> statement-breakpoint
CREATE INDEX "export_jobs_state_created_idx" ON "export_jobs" ("state", "created_at");
--> statement-breakpoint
CREATE INDEX "export_jobs_result_expiry_idx" ON "export_jobs" ("result_expires_at");
--> statement-breakpoint

CREATE TABLE "export_job_problems" (
  "job_id" uuid NOT NULL REFERENCES "export_jobs" ("id") ON DELETE CASCADE,
  "position" integer NOT NULL,
  "problem_id" bigint NOT NULL REFERENCES "problems" ("id") ON DELETE RESTRICT,
  "revision_id" uuid NOT NULL REFERENCES "problem_revisions" ("id") ON DELETE RESTRICT,
  "included_file_categories" jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT "export_job_problems_pk" PRIMARY KEY ("job_id", "position"),
  CONSTRAINT "export_job_problems_problem_revision_fk"
    FOREIGN KEY ("problem_id", "revision_id")
    REFERENCES "problem_revisions" ("problem_id", "id") ON DELETE RESTRICT,
  CONSTRAINT "export_job_problems_position_ck" CHECK ("position" >= 0)
);
--> statement-breakpoint
CREATE UNIQUE INDEX "export_job_problems_problem_uq"
  ON "export_job_problems" ("job_id", "problem_id");
--> statement-breakpoint
CREATE INDEX "export_job_problems_revision_idx" ON "export_job_problems" ("revision_id");
--> statement-breakpoint

CREATE TABLE "audit_events" (
  "id" bigint GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME "audit_events_id_seq" START WITH 1) PRIMARY KEY,
  "occurred_at" timestamptz NOT NULL DEFAULT now(),
  "actor_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "subject_user_id" bigint REFERENCES "users" ("id") ON DELETE RESTRICT,
  "request_id" uuid NOT NULL,
  "action" varchar(160) NOT NULL,
  "object_type" varchar(80) NOT NULL,
  "object_id" varchar(160),
  "result" "audit_result" NOT NULL,
  "reason_code" varchar(160),
  "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT "audit_events_action_ck" CHECK (length(btrim("action")) > 0),
  CONSTRAINT "audit_events_object_type_ck" CHECK (length(btrim("object_type")) > 0)
);
--> statement-breakpoint
CREATE INDEX "audit_events_occurred_idx" ON "audit_events" ("occurred_at");
--> statement-breakpoint
CREATE INDEX "audit_events_actor_occurred_idx"
  ON "audit_events" ("actor_user_id", "occurred_at");
--> statement-breakpoint
CREATE INDEX "audit_events_object_occurred_idx"
  ON "audit_events" ("object_type", "object_id", "occurred_at");
--> statement-breakpoint
CREATE INDEX "audit_events_request_idx" ON "audit_events" ("request_id");
--> statement-breakpoint

CREATE FUNCTION "prevent_audit_event_changes"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "audit_events_no_update_or_delete"
BEFORE UPDATE OR DELETE ON "audit_events"
FOR EACH ROW EXECUTE FUNCTION "prevent_audit_event_changes"();
--> statement-breakpoint
